version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: getstok_api_dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth_network
    restart: always