version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: getstok_postgres
    ports:
      - "5433:5432"
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - auth_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ybandung"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge