version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: getstok_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth_network
    restart: always