version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT_NOTIFICATION_SERVICE:-8081}:${PORT_NOTIFICATION_SERVICE:-8081}"
    networks:
      - notification-network
    environment:
      - DB_HOST=notification-db

  notification-service-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: notification-service-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT_NOTIFICATION_SERVICE:-8081}:${PORT_NOTIFICATION_SERVICE:-8081}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - notification-network
    command: node main.js
    environment:
      - DB_HOST=notification-db

networks:
  notification-network:
    driver: bridge

volumes:
  notification-postgres-data:
    driver: local