FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies including devDependencies
RUN npm install

# Set environment to development
ENV NODE_ENV=development

# Expose the port
EXPOSE ${PORT_NOTIFICATION_SERVICE:-8081}

# Start the application in development mode directly with node
CMD ["node", "main.js"]